#!/bin/bash
source CONFIG
echo echo url="https://www.duckdns.org/update?domains=${domain}&token=${token}&ip=" \| curl -k -o ~/duckdns/duck.log -K - > ~/duckdns.sh
chmod 700 ~/duckdns.sh

(crontab -l 2>/dev/null; echo "*/5 /home/pi/duckdns.sh") | crontab -
